### ISSUE TITLE
Single period projects for EUTF

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3232]
To enable the "free form" workflow for the EUTF results framework the following sub tasks have been identified:

- [x] Set control of the features in the Django settings #3233 
- [x] Management command that creates one period for each indicator #3234
- [x] Automatically populate new indicators for EUTF projects with one period #3235
- [x] Change the behaviour of the **Needs reporting** filter in the results framework to activate if all updates are older than some timeout. Ignore locking of periods and hide UI elements related to locking #3236
- [x] When showing period dates they should be replaced with the start and end dates of the project of the current indicator period #3237
