### ISSUE TITLE
Deprecation(django): Use on_delete on `ForeignKey`

### ISSUE THREAD

**Issue by MichaelAkvo** [akvo/akvo-rsr#4675]
`on_delete` was made mandatory option when creating `ForeignKey`s (and descendants like `OneToOneField`).

# TODO

 - [ ] Use `on_delete=` in non-migration models
 - [ ] [squash migrations](https://docs.djangoproject.com/en/3.2/topics/migrations/#squashing-migrations)
 - [ ] Plan deployment on production (probably need input from @muloem and/or @tangrammer )  
    * stop django backend (no more db requests)
    * backup db
    * run migration
    * restart django backend
    * Check if everything is well
    * Hopefully there won't be a need to restore the db
