### ISSUE TITLE
Upgrade of Django from 1.4 to 1.6

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#544]
Based on the conversations we have held we have a plan to upgrade our Django version for RSR:
https://github.com/akvo/akvo-rsr/issues/328
https://github.com/akvo/akvo-rsr/issues/522

 We will do this in several internal steps moving up a single version in each step. Assuming that we hit on no major issues, we will be releasing the work done in a single step when we have reached the latest 1.7 version.
- [x] Pre-Upgrade Steps #545 
- [x] 1.5 Upgrade
- [x] Post 1.5 / Pre 1.6 Steps #546 
- [x] 1.6 Upgrade
- [x] Post 1.6 / Pre 1.7 Steps #547
